""" CONSTANT """

'''
User Type
'''
USER_TYPE_CLIENT = 1
USER_TYPE_SERVICE_PROVIDER = 2
USER_TYPE_ADMIN = 3

'''
Service Type
'''
SERVICE_TYPE_ELECTRONIC = 1
SERVICE_TYPE_VEHICLE = 2

'''
Order Status
'''
ORDER_STATUS_PENDING = 1
ORDER_STATUS_CONFIRMED = 2
ORDER_STATUS_PROCESSING = 3
ORDER_STATUS_COMPLETED = 4
ORDER_STATUS_USER_CANCELLED = 5
ORDER_STATUS_SERVICE_PROVIDER_CANCELLED = 6
ORDER_STATUS_INCOMPLETE_ORDER = 7
